// Code generated by hertz generator.

package main

import (
	"github.com/XZ0730/tireCV/biz/dal"
	"github.com/cloudwego/hertz/pkg/app/server"
)

func Init() {
	dal.Init()
}

func main() {
	Init()
	h := server.New(server.WithHostPorts("0.0.0.0:8083"))

	register(h)
	h.Spin()
}
