// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	calculate "github.com/XZ0730/tireCV/biz/router/calculate"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	calculate.Register(r)

}
